### ISSUE TITLE
Feature: Allow usage with level restrictions

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-KnockbackRestrict#2]
- Allow ADMFLAG_KICK to use commands.
- Make a level system with max ban time (cvar)
Based on flag, they can't do args > cvar of their flag :
  - Kick > 720 (12 hours)
  - Ban 20160 (2wk)
  - Rcon 40320 (4wk)

And instead of set the Default Value when args > max value (for flag) use Max value.

**Comment by Dolly132** [comment]
Done. Pushed a pull request for it.
